1.3.1 Задание
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [5]:
import numpy as np
x = np.zeros(64).reshape(8,8)
x[1::2, ::2]=1
x[::2, 1::2]=1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


1.3.2 Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.

In [9]:
import numpy as np
x = np.tile(np.arange(5),5).reshape(5,5)
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3 Задание
Создать массив 3x3x3 со случайными значениями.

In [12]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.67223441 0.29278222 0.49800752]
  [0.43550082 0.63766205 0.27081296]
  [0.5222699  0.81257381 0.57357975]]

 [[0.17878246 0.79707698 0.10274204]
  [0.30956832 0.11997074 0.66526427]
  [0.97388051 0.01800939 0.84011762]]

 [[0.77612782 0.08882171 0.00253262]
  [0.43012202 0.19914449 0.83632815]
  [0.44021168 0.20541059 0.94101098]]]


1.3.4 Задание
Создать матрицу с 0 внутри, и 1 на границах.

In [13]:
import numpy as np
rows, cols = 5, 5

matrix = np.zeros((rows, cols), dtype=int)

matrix[0, :] = 1
matrix[-1, :] = 1 
matrix[:, 0] = 1
matrix[:, -1] = 1 

print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


1.3.5 Задание
Создайте массив и отсортируйте его по убыванию.

In [22]:
import numpy as np
n = 1000
x = np.random.random(n)
x=np.sort(x)[::-1]
print(x)

[0.99971376 0.99914372 0.99898713 0.99479138 0.99458353 0.99423522
 0.99409696 0.99361573 0.991138   0.99042368 0.98852393 0.98509024
 0.98347126 0.98317289 0.98141962 0.97982023 0.97845333 0.97828357
 0.97814499 0.97695762 0.97623961 0.97362752 0.97362517 0.97258661
 0.97180703 0.9710761  0.97044892 0.96926489 0.969129   0.96885997
 0.96839973 0.96828966 0.96723354 0.96685021 0.96445934 0.96345681
 0.9628843  0.96258396 0.9594169  0.95906248 0.9587249  0.95842988
 0.95714885 0.95635745 0.9553598  0.95509257 0.95482051 0.95334178
 0.95174866 0.94919222 0.94855459 0.94284976 0.94132608 0.94123381
 0.9409508  0.9384527  0.93808702 0.93753438 0.93721046 0.93686134
 0.93443749 0.93426099 0.93268841 0.93185715 0.93008352 0.92994282
 0.92824373 0.92819071 0.92813062 0.92697422 0.92483758 0.92322805
 0.92287018 0.92238403 0.9197578  0.91888707 0.9186284  0.91852392
 0.91640685 0.91604932 0.91568781 0.91567864 0.91561512 0.91220984
 0.91201561 0.91138032 0.90938856 0.90844243 0.90787    0.9065

1.3.6 Задание
Создайте матрицу, выведите ее форму, размер и размерность.

In [64]:
import numpy as np
rows, cols = 5, 5
arr = np.random.rand(rows,cols)
print(arr)
print("Форма матрицы:")
print(arr.shape)
print("Размер матрицы:")
print(arr.size)
print("Размерность матрицы:")
print(arr.ndim)

[[0.51825745 0.77321767 0.67462882 0.95599722 0.25297225]
 [0.81963399 0.44664518 0.23379295 0.887712   0.26154218]
 [0.1571143  0.44397621 0.50206065 0.91691765 0.54216135]
 [0.84629463 0.54615081 0.5662085  0.22564154 0.71480572]
 [0.88661045 0.6998676  0.30426227 0.08849755 0.27574119]]
Форма матрицы:
(5, 5)
Размер матрицы:
25
Размерность матрицы:
2


2.3.1 Задание
Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [6]:
ax, ay, bx, by = 1,2,3,4
print(((ax-bx)**2+(ay-by)**2)**0.5)

2.8284271247461903


2.3.2 Задание
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [65]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/abolone.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   

   Viscera weight  Shell weight  Rings  
0          0.1010         0.150     15  
1          0.0485         0.070      7  
2          0.1415         0.210      9  
3          0.1140         0.155     10  
4          0.0395         0.055      7

2.3.3 Задание
Проделайте с получившемся из предыдущего задания фреймом данных 
те же действия, что и в примерах 2.2.5-2.2.7.

In [57]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/abolone.csv'
dataframe = pd.read_csv(url, on_bad_lines='skip')
print('размер',dataframe.shape)
print('описательная статистика:\n',dataframe.describe())
print(dataframe.iloc[8:12])
dataframe[dataframe['Gender']=='M'].head(5)

размер (4177, 9)
описательная статистика:
             Length     Diameter       Height  Whole weight  Shucked weight  \
count  4177.000000  4177.000000  4177.000000   4177.000000     4177.000000   
mean      0.523992     0.407881     0.139516      0.828742        0.359367   
std       0.120093     0.099240     0.041827      0.490389        0.221963   
min       0.075000     0.055000     0.000000      0.002000        0.001000   
25%       0.450000     0.350000     0.115000      0.441500        0.186000   
50%       0.545000     0.425000     0.140000      0.799500        0.336000   
75%       0.615000     0.480000     0.165000      1.153000        0.502000   
max       0.815000     0.650000     1.130000      2.825500        1.488000   

       Viscera weight  Shell weight        Rings  
count     4177.000000   4177.000000  4177.000000  
mean         0.180594      0.238831     9.933684  
std          0.109614      0.139203     3.224169  
min          0.000500      0.001500     1.000000  

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
0       M   0.455     0.365   0.095        0.5140          0.2245   
1       M   0.350     0.265   0.090        0.2255          0.0995   
3       M   0.440     0.365   0.125        0.5160          0.2155   
8       M   0.475     0.370   0.125        0.5095          0.2165   
11      M   0.430     0.350   0.110        0.4060          0.1675   

    Viscera weight  Shell weight  Rings  
0           0.1010         0.150     15  
1           0.0485         0.070      7  
3           0.1140         0.155     10  
8           0.1125         0.165      9  
11          0.0810         0.135     10

3.3.2 Задание
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [63]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
df = pd.read_csv(url)

print("Первые несколько строк фрейма данных:")
print(df.head())

# Нормализация первого числового признака (sepal_length_cm) с использованием минимаксного преобразования
df['sepal_length_cm'] = MinMaxScaler().fit_transform(df[['sepal_length_cm']])

# Нормализация второго числового признака (sepal_width_cm) с использованием z-масштабирования
df['sepal_width_cm'] = StandardScaler().fit_transform(df[['sepal_width_cm']])

print("\nПервые нескольких строк фрейма данных после нормализации:")
print(df.head())


Первые несколько строк фрейма данных:
   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

Первые нескольких строк фрейма данных после нормализации:
   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2